server:
  port: 21010

spring:
  application:
    name: mms-manager
  datasource:
    url: jdbc:mysql://82.157.252.31:3306/mms-manager?useSSL=false&autoReconnect=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Team@4gr.Mysql

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

mms:
  security:
    ignored-paths:
      - /v3/api-docs/**
      - /doc.html
      - /v3/api-docs/default
  crypto:
    rsa:
      private-key-file: mms-manager-private.der
      public-key-file: mms-manager-public.pem

# springdoc-openapi????
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: ink.labrador.mmsmanager.controller

knife4j:
  enable: true
  setting:
    language: zh_cn